### ISSUE TITLE
Data split for table 1 experiments

### ISSUE THREAD

**Issue by atanas1054** [nvr-avg/adaptive-prediction#1]
Hello,

Thank you for the repo. Can you please share the exact ETH/UCY data splits used for creating table 1 in the paper?

**Comment by BorisIvanovic** [comment]
Hello,

We used [trajdata](https://github.com/NVlabs/trajdata) to provide data in this project. To create table 1 in the paper, we trained our models on the training split of the indicated source dataset and evaluated them on the entire indicated target dataset. For example, in the case of "A2B" we would train on `eupeds_eth-train` and evaluate on `eupeds_hotel-test_loo` (which provides the entire hotel scene).

Hope this helps!
