### ISSUE TITLE
Reproduction of PECNet result in table 1

### ISSUE THREAD

**Issue by haofuly** [nvr-avg/adaptive-prediction#4]
Hi, thanks for sharing the code.
In fact, I found it hard to reproduce the result of PECNet in table 1, such as the 1.97(ADE)/ 3.33(FDE) on A2B dataset.
I think it's because the specific config or dataset format of PECNet. Can you share your reproduce procedure?

**Comment by BorisIvanovic** [comment]
Hi @haofuly , thank you for your question.

We used the values from https://arxiv.org/abs/2203.05046, please follow up with the authors of T-GNN for the exact reproduction procedure.
